language: python
python:
    - "3.9"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"
        - $HOME/.cache/pip

env:

install:
    - pip install --upgrade pip setuptools importlib-metadata
    - pip install -U platformio
    - pio pkg install
    - pio pkg update


script:
    # Don't build native, used only for unit tests
    - pio ci --project-conf=platformio.ini --lib="." -e nodemcuv2 -e esp32 -e m5stickc -e m5stickcplus src
    - pio test -e native -v